### ISSUE TITLE
Variable connection count in time and considerably less than max_connections

### ISSUE THREAD

**Issue by eguzki** [socketry/async-pool#10]
Hi,

In https://github.com/3scale/apisonator, we have been using Async-pool @0.2.0 some time for the pool connections to redis with the aysnc-redis gem (https://github.com/socketry/async-redis). We detected the same memory leak that was reported in #6. The memory leak was fixed in v0.3.4. We have tested that. Thanks a lot for the fix. However starting in that version, v0.3.4, up to v0.3.9, we have detected one connection management issue. The connection management issue does not happen in v0.3.3. I have tested the following versions: v0.3.5, v0.3.6, v0.3.7, v0.3.8,  v0.3.9 with the same connection management issue described below. 

in version <= v0.3.3, the number of connections to redis remained stable to the `:limit` configured when traffic load is high enough. We switched to version `v0.3.9` and (with the same traffic load), the average number of connections to redis was considerably reduced to, let's say ~30% of the limit. Furthermore, the connection themselves were not stable and we have monitorized **_connections being _created_ and _destroyed_ continuously_**, as said before, having an average of total connections ~30% of the `:limit` configured. The penalty of creating and destroying connections continuously has a considerable impact on the time required for the jobs sending commands to redis to complete.

I attach a timeline of the connection count when we deployed `v0.3.9`. Obviously, the deployment was reverted back ~20 minutes later, back to v0.2.0.
![connection_count](https://user-images.githubusercontent.com/881529/144235530-21ce4b1b-f865-43d4-b0a6-eb107b87e1b2.png)

We look forward to deploying the memory leak fix, but currently the leak fix introduces the connection management issue and we cannot have both issues fixed. 

We really appreciate some support here

cc @roivaz

**Comment by eguzki** [comment]
Additional note: it might be that the pool is using the max number of connections configured, but since the connections are being created and destroyed continuously, the prometheus metric, at sampling moment, only reports 30% as connections established.

In that case, the issue would be connections being created and destroyed continuously and not being reused.

**Comment by eguzki** [comment]
Hi, I have been digging into this issue to confirm connection management issue. I have deployed a `socat` relay server as "proxy" between our redis clients and redis instance. With `-d -d` flags, it shows logs about connection being created or destroyed. 

The clients with `async-pool` v0.3.3 create connections up to max configured (10 in the test). The connections are not killed and they are reused. When clients do their job multiple times, they reuse the same connections. Socat does not show connections being destroyed. 10 connections are opened and reused for many redis commands.

```
2021/12/02 12:32:44 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:41:24 socat[1] N accepting connection from AF=2 10.128.2.112:43828 on AF=2 10.128.2.109:6379
2021/12/02 12:41:24 socat[1] N forked off child process 6
2021/12/02 12:41:24 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:41:24 socat[6] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:41:24 socat[6] N successfully connected from local address AF=2 10.128.2.109:47572
2021/12/02 12:41:24 socat[6] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:43:31 socat[1] N accepting connection from AF=2 10.128.2.112:45808 on AF=2 10.128.2.109:6379
2021/12/02 12:43:31 socat[1] N forked off child process 7
2021/12/02 12:43:31 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:43:31 socat[7] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:43:31 socat[7] N successfully connected from local address AF=2 10.128.2.109:49552
2021/12/02 12:43:31 socat[7] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:43:31 socat[1] N accepting connection from AF=2 10.128.2.112:45812 on AF=2 10.128.2.109:6379
2021/12/02 12:43:31 socat[1] N forked off child process 8
2021/12/02 12:43:31 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:43:31 socat[8] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:43:31 socat[8] N successfully connected from local address AF=2 10.128.2.109:49556
2021/12/02 12:43:31 socat[8] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46382 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 9
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[9] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[9] N successfully connected from local address AF=2 10.128.2.109:50126
2021/12/02 12:44:09 socat[9] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46386 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 10
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[10] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[10] N successfully connected from local address AF=2 10.128.2.109:50132
2021/12/02 12:44:09 socat[10] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46388 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 11
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[11] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[11] N successfully connected from local address AF=2 10.128.2.109:50134
2021/12/02 12:44:09 socat[11] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46394 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 12
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46396 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[12] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[1] N forked off child process 13
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[12] N successfully connected from local address AF=2 10.128.2.109:50140
2021/12/02 12:44:09 socat[12] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[13] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[13] N successfully connected from local address AF=2 10.128.2.109:50142
2021/12/02 12:44:09 socat[13] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46402 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 14
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[14] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[14] N successfully connected from local address AF=2 10.128.2.109:50146
2021/12/02 12:44:09 socat[14] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:44:09 socat[1] N accepting connection from AF=2 10.128.2.112:46406 on AF=2 10.128.2.109:6379
2021/12/02 12:44:09 socat[1] N forked off child process 15
2021/12/02 12:44:09 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:44:09 socat[15] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:44:09 socat[15] N successfully connected from local address AF=2 10.128.2.109:50150
2021/12/02 12:44:09 socat[15] N starting data transfer loop with FDs [6,6] and [5,5]
``` 

Now, I deployed the same client, with only one change in the gemspec, async-pool changed from 0.3.3 to 0.3.4. After running few jobs by the client, the socat shows connections being created and destroyed **continuously**. The logs only show few seconds of the test, but you can make sure this is happening all the time:
```
2021/12/02 12:54:34 socat[1] N accepting connection from AF=2 10.128.2.117:35736 on AF=2 10.128.2.109:6379
2021/12/02 12:54:34 socat[1] N forked off child process 859
2021/12/02 12:54:34 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:54:34 socat[1] N accepting connection from AF=2 10.128.2.117:35738 on AF=2 10.128.2.109:6379
2021/12/02 12:54:34 socat[1] N forked off child process 860
2021/12/02 12:54:34 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:54:34 socat[1] N accepting connection from AF=2 10.128.2.117:35740 on AF=2 10.128.2.109:6379
2021/12/02 12:54:34 socat[1] N forked off child process 861
2021/12/02 12:54:34 socat[1] N listening on AF=2 0.0.0.0:6379
2021/12/02 12:54:34 socat[859] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:54:34 socat[860] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:54:34 socat[860] N successfully connected from local address AF=2 10.128.2.109:34952
2021/12/02 12:54:34 socat[860] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:54:34 socat[861] N opening connection to AF=2 10.128.2.97:6379
2021/12/02 12:54:34 socat[861] N successfully connected from local address AF=2 10.128.2.109:34954
2021/12/02 12:54:34 socat[861] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:54:34 socat[859] N successfully connected from local address AF=2 10.128.2.109:34950
2021/12/02 12:54:34 socat[859] N starting data transfer loop with FDs [6,6] and [5,5]
2021/12/02 12:54:34 socat[861] N socket 1 (fd 6) is at EOF
2021/12/02 12:54:34 socat[861] N socket 2 (fd 5) is at EOF
2021/12/02 12:54:34 socat[861] N exiting with status 0
2021/12/02 12:54:34 socat[1] N childdied(): handling signal 17
```

Hopefully it helps to fix the issue

**Comment by ioquatix** [comment]
Thanks, I will try to sort this out. This change was introduced to try and avoid lots of connections sitting around unused but it looks like a general regression to performance on a number of fronts so I might revert the change that introduced this behaviour.

**Comment by eguzki** [comment]
:+1: Let me know if I can help you with some tests

If you revert all the changes, the memory leak reported in #6 will show up again

**Comment by eguzki** [comment]
@ioquatix any estimation about when this can be fixed?

**Comment by ioquatix** [comment]
I'll hopefully have some time in February to address this.

**Comment by ioquatix** [comment]
Okay, so first things first, let's solve the performance issue.

https://github.com/socketry/async-pool/commit/748387c72074a0dc07aafb20ee6980b0b1ca5c3d reverts the `overflowing?` logic which was causing connections to be retired too rapidly.

I could reproduce the performance issue and this change brings us back to the previous good baseline.

In addition, I've added a concurrency tweak which controls how many tasks can simultaneously connect - increasing this to limit (the default if limit is specified) gives the best possible throughput.

Next, let's revisit the connection overflow/usage/memory leaks. I believe we have a couple of options to address this, probably by maintaining a high water mark and having the background task periodically wake up and prune available connections.

**Comment by ioquatix** [comment]
I've added the memory leak example from #6: https://github.com/socketry/async-pool/blob/main/examples/memory/leak.rb

I tested it with this latest round of changes and it looks okay to me:

```
> bundle exec ./leak.rb
available size 1, unique 1
```

@bruno- if you have some time do you mind checking it's working as expected?

**Comment by ioquatix** [comment]
Regarding pool size limits and memory usage, the `limit:` control is one way and sets a maximum upper bound which changes the latency profile of the pool significantly. We could consider making this an `attr_accessor`. I think the pool itself is a data structure to efficiently manage pooled connections but I don't think it should care about application level concerns relating to usage patterns. For this, I think we should introduce a `Async::Pool::Policy` which can be potentially shared between pools (if it's stateless). I'd rather avoid going down this path but it would allow pools to be configured to reflect application level usage patterns which we will not be able to completely encode into the default implementation.

**Comment by bruno-** [comment]
@ioquatix I've checked the example and reviewed the code and it looks good to me! 👍 

> For this, I think we should introduce a Async::Pool::Policy which can be potentially shared between pools (if it's stateless).

I'm looking forward to having more control over the pool behavior.

**Comment by eguzki** [comment]
Working like a charm. :medal_military: 

Connection management stable and no memory leak detected.

**Comment by ioquatix** [comment]
Thanks for reporting back!
