### ISSUE TITLE
v0.5.0 specifies Ruby v2.5+, but seems to require Ruby v3+

### ISSUE THREAD

**Issue by fallwith** [socketry/async-pool#19]
The recent publishing of v0.5.0 caused our CI system to grab it for use with Ruby v2, which failed to parse the Ruby v3 syntax located at `async-pool-0.5.0/lib/async/pool/controller.rb:56`.

I noticed that v0.6.0 and v0.6.1 were published shortly after v0.5.0 and that they both declare a dependency on Ruby v3.1+.

It is possible to either yank v0.5.0 or clobber it with a version that declares a Ruby v3.1+ dependency?

If not, here's the workaround we used for our Ruby v2.x tests for others to potentially benefit from:
https://github.com/newrelic/newrelic-ruby-agent/pull/2585

**Comment by ioquatix** [comment]
Thanks for this report, I'll fix it.

**Comment by ioquatix** [comment]
Okay, I've yanked 0.5.0 - it was the quick fix.

The reason why, is that actually v0.5.0 might have some level of instability, I'm still investigating it. I recommend sticking with v0.4.0 for now. v0.6.1 reverts one of the changes, so it is probably okay, but I don't want to support super old Ruby versions either.

**Comment by fallwith** [comment]
Thanks, @ioquatix!
